name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  awesome_dialog: ^3.1.0
  cloud_firestore: ^4.13.5
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.2
  firebase_core: 2.24.2
  firebase_storage: ^11.5.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: 4.6.6
  google_fonts: ^6.1.0
  image_picker: ^1.0.5
  intl: ^0.18.1
  path_provider: ^2.1.1
  syncfusion_flutter_datepicker: ^21.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
